/**
 * Point 54: the cryptographic components, tested the way cryptographic code has to be —
 * against published vectors first, and then against everything an attacker would send.
 *
 * The nine kinds the brief asks for, and where they are:
 *
 * | Kind | Here | Also |
 * | --- | --- | --- |
 * | known-answer | `describe("known answers")` | RFC 5869 HKDF vectors in `hkdf.test.ts`, BIP-39 in `recovery.test.ts` |
 * | negative | `describe("negative")` | signature refusals in `protocol.test.ts` |
 * | malformed input | `describe("malformed input")` | `padding.test.ts`, `uploads.test.ts` |
 * | replay | `describe("replay")` | consumed-message replay in `protocol.test.ts` |
 * | corrupted ciphertext | `describe("corrupted ciphertext")` | backup tampering in `backup.test.ts` |
 * | wrong key | `describe("the wrong key")` | vault round-trip in `protocol.test.ts` |
 * | wrong identity | `describe("the wrong identity")` | safety numbers in `verification.test.ts` |
 * | nonce misuse | `describe("nonces")` | — |
 * | session reset | `describe("session reset")` | linking in `linking.test.ts` |
 *
 * Vectors are copied from the specifications, not generated by this code: a known-answer
 * test whose answer came out of the implementation it tests proves only that the code is
 * deterministic.
 */
import { beforeAll, describe, expect, it } from "vitest";
import { sodium, sodiumReady, randomBytes } from "../src/shared/crypto/sodium.ts";
import { aeadDecrypt, aeadEncrypt, NONCE_BYTES } from "../src/shared/crypto/aead.ts";
import { dh, createDeviceIdentity, safetyNumber } from "../src/shared/crypto/identity.ts";
import { pad, unpad } from "../src/shared/crypto/padding.ts";
import { decryptFile, encryptFile } from "../src/shared/crypto/file.ts";
import {
  decodeMessage,
  encodeMessage,
  ratchetDecrypt,
  ratchetEncrypt,
} from "../src/shared/crypto/ratchet.ts";
import {
  acceptSession,
  decryptText,
  encryptText,
  openSession,
} from "../src/shared/crypto/session.ts";
import {
  deriveAccountKeys,
  generateMasterKey,
  openVault,
  sealVault,
  unwrapMasterKey,
  wrapMasterKey,
} from "../src/shared/crypto/vault.ts";
import { utf8 } from "../src/shared/encoding.ts";

const hex = (text: string) => Uint8Array.from(text.match(/../g)!.map((byte) => parseInt(byte, 16)));

/**
 * `crypto_core_hchacha20` is in the sumo build we ship but missing from its type package,
 * so it is reached through one narrow cast rather than by loosening `sodium()` everywhere.
 */
const hchacha20 = (input: Uint8Array, key: Uint8Array): Uint8Array =>
  (sodium() as unknown as { crypto_core_hchacha20(i: Uint8Array, k: Uint8Array): Uint8Array })
    .crypto_core_hchacha20(input, key);
const toHex = (bytes: Uint8Array) => Buffer.from(bytes).toString("hex");

/** Argon2id at product parameters takes a second; the plumbing is what these tests check. */
const FAST_KDF = { opsLimit: 1, memLimit: 8192 };

beforeAll(async () => {
  await sodiumReady();
});

/** Two peers with a live session, built the way `session.ts` intends. */
function pair() {
  const alice = createDeviceIdentity(1);
  const bob = createDeviceIdentity(1);
  const outgoing = openSession(alice.identity, {
    identityKey: bob.identity.publicKey,
    signedPreKeyId: bob.signedPreKey.keyId,
    signedPreKey: bob.signedPreKey.keyPair.publicKey,
    signedPreKeySignature: bob.signedPreKeySignature,
    oneTimePreKeyId: bob.oneTimePreKeys[0]!.keyId,
    oneTimePreKey: bob.oneTimePreKeys[0]!.keyPair.publicKey,
  });
  const bobState = acceptSession(
    bob.identity,
    bob.signedPreKey,
    bob.oneTimePreKeys[0]!,
    outgoing.invite,
  );
  return { alice, bob, aliceState: outgoing.state, bobState, invite: outgoing.invite };
}

/* ------------------------------- known answers ------------------------------- */

describe("known answers", () => {
  it("matches RFC 8439 §2.8.2 for ChaCha20-Poly1305", () => {
    const key = hex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f");
    const nonce = hex("070000004041424344454647");
    const aad = hex("50515253c0c1c2c3c4c5c6c7");
    const plaintext = utf8(
      "Ladies and Gentlemen of the class of '99: If I could offer you only one tip for the future, sunscreen would be it.",
    );
    const sealed = sodium().crypto_aead_chacha20poly1305_ietf_encrypt(
      plaintext,
      aad,
      null,
      nonce,
      key,
    );
    expect(toHex(sealed)).toBe(
      "d31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d63dbea45e8ca967128" +
        "2fafb69da92728b1a71de0a9e060b2905d6a5b67ecd3b3692ddbd7f2d778b8c9803aee328091b58fa" +
        "b324e4fad675945585808b4831d7bc3ff4def08e4b7a9de576d26586cec64b6116" +
        "1ae10b594f09e26a7e902ecbd0600691",
    );
  });

  it("matches draft-irtf-cfrg-xchacha-03 §A.1 for HChaCha20", () => {
    const key = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f");
    const input = hex("000000090000004a0000000031415927");
    expect(toHex(hchacha20(input, key))).toBe(
      "82413b4227b27bfed30e42508a877d73a0f9e4d58a74a853c12ec41326d3ecdc",
    );
  });

  it("is the published composition: XChaCha20-Poly1305 = HChaCha20 then ChaCha20-Poly1305", () => {
    // This is what makes the two vectors above cover `aead.ts` rather than only libsodium:
    // our AEAD is XChaCha20-Poly1305, and the specification defines it as HChaCha20 over
    // the first 16 nonce bytes followed by the IETF AEAD with the remaining 8.
    const key = randomBytes(32);
    const nonce = randomBytes(NONCE_BYTES);
    const plaintext = utf8("the composition, not the library");
    const aad = utf8("associated");

    const subKey = hchacha20(nonce.subarray(0, 16), key);
    const shortNonce = new Uint8Array(12);
    shortNonce.set(nonce.subarray(16), 4);
    const expected = sodium().crypto_aead_chacha20poly1305_ietf_encrypt(
      plaintext,
      aad,
      null,
      shortNonce,
      subKey,
    );
    expect(toHex(aeadEncrypt(key, plaintext, aad, nonce))).toBe(toHex(expected));
  });

  it("matches RFC 7748 §6.1 for X25519", () => {
    const alicePrivate = hex("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a");
    const bobPublic = hex("de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f");
    expect(toHex(dh(alicePrivate, bobPublic))).toBe(
      "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742",
    );
  });
});

/* --------------------------------- negative --------------------------------- */

describe("negative", () => {
  it("refuses a key or a nonce of the wrong size instead of padding it", () => {
    const key = randomBytes(32);
    const nonce = randomBytes(NONCE_BYTES);
    expect(() => aeadEncrypt(randomBytes(31), utf8("x"), new Uint8Array(), nonce)).toThrow(
      /bad key length/,
    );
    expect(() => aeadEncrypt(key, utf8("x"), new Uint8Array(), randomBytes(12))).toThrow(
      /bad nonce length/,
    );
    expect(() => aeadDecrypt(key, randomBytes(48), new Uint8Array(), randomBytes(23))).toThrow(
      /bad nonce length/,
    );
  });

  it("refuses associated data that does not match", () => {
    const key = randomBytes(32);
    const nonce = randomBytes(NONCE_BYTES);
    const sealed = aeadEncrypt(key, utf8("secret"), utf8("order-1"), nonce);
    expect(() => aeadDecrypt(key, sealed, utf8("order-2"), nonce)).toThrow();
    expect(() => aeadDecrypt(key, sealed, new Uint8Array(), nonce)).toThrow();
  });

  it("refuses a delivery decrypted under a different order id", () => {
    const file = encryptFile("order-1", utf8("the licence key"));
    expect(() => decryptFile("order-2", file.key, file.nonce, file.ciphertext)).toThrow();
    expect(new TextDecoder().decode(decryptFile("order-1", file.key, file.nonce, file.ciphertext)))
      .toBe("the licence key");
  });

  it("refuses an empty or oversized file rather than encrypting nothing", () => {
    expect(() => encryptFile("order-1", new Uint8Array())).toThrow(/empty/);
    expect(() => encryptFile("order-1", new Uint8Array(4 * 1024 * 1024))).toThrow(/larger than/);
  });
});

/* ------------------------------ malformed input ------------------------------ */

describe("malformed input", () => {
  it("refuses a message that is not the current wire format", () => {
    for (const encoded of [
      "",
      "{",
      "[]",
      JSON.stringify({ v: 1, h: "AA", ct: "AA" }),
      JSON.stringify({ v: 2, h: "AA" }),
      JSON.stringify({ v: 2, ct: "AA" }),
      JSON.stringify({ v: "2", h: "AA", ct: "AA" }),
    ]) {
      expect(() => decodeMessage(encoded), encoded).toThrow();
    }
  });

  it("refuses a sealed header of the wrong length before deriving anything", () => {
    const { aliceState, bobState } = pair();
    const message = ratchetEncrypt(aliceState, utf8("hello"));
    for (const header of [
      new Uint8Array(0),
      message.encryptedHeader.subarray(0, 10),
      new Uint8Array([...message.encryptedHeader, 0]),
    ]) {
      expect(() => ratchetDecrypt(bobState, { ...message, encryptedHeader: header })).toThrow(
        /failed authentication/,
      );
    }
    // The session survived every one of them, and still opens the real message.
    expect(new TextDecoder().decode(ratchetDecrypt(bobState, message))).toBe("hello");
  });

  it("refuses a vault sealed by an incompatible version", () => {
    const masterKey = generateMasterKey();
    const sealed = sealVault(masterKey, utf8("{}"));
    expect(() => openVault(masterKey, { ...sealed, v: 2 as unknown as 3 })).toThrow(
      /unsupported version/,
    );
    expect(() => openVault(masterKey, { ...sealed, data: "not base64 !!" })).toThrow();
  });

  it("refuses padding that no longer carries its marker", () => {
    const padded = pad(utf8("hello"));
    expect(() => unpad(new Uint8Array(padded.length))).toThrow(/malformed padding/);
    expect(() => unpad(new Uint8Array())).toThrow(/malformed padding/);
    expect(() => unpad(Uint8Array.of(1, 2, 3))).toThrow(/malformed padding/);
  });
});

/* ---------------------------------- replay ---------------------------------- */

describe("replay", () => {
  it("refuses the same message a second time, and the third, and the tenth", () => {
    const { aliceState, bobState } = pair();
    const message = ratchetEncrypt(aliceState, utf8("only once"));
    expect(new TextDecoder().decode(ratchetDecrypt(bobState, message))).toBe("only once");
    for (let attempt = 0; attempt < 10; attempt += 1) {
      expect(() => ratchetDecrypt(bobState, message)).toThrow(/failed authentication/);
    }
  });

  it("refuses a replayed out-of-order message once its stored key is spent", () => {
    const { aliceState, bobState } = pair();
    const first = ratchetEncrypt(aliceState, utf8("one"));
    const second = ratchetEncrypt(aliceState, utf8("two"));
    // The second arrives first: the key for `first` is stored as skipped, then used.
    expect(new TextDecoder().decode(ratchetDecrypt(bobState, second))).toBe("two");
    expect(new TextDecoder().decode(ratchetDecrypt(bobState, first))).toBe("one");
    expect(() => ratchetDecrypt(bobState, first)).toThrow(/failed authentication/);
    expect(() => ratchetDecrypt(bobState, second)).toThrow(/failed authentication/);
  });

  it("refuses a message replayed into a different session", () => {
    const first = pair();
    const second = pair();
    const message = ratchetEncrypt(first.aliceState, utf8("for one session only"));
    expect(() => ratchetDecrypt(second.bobState, message)).toThrow(/failed authentication/);
  });
});

/* ----------------------------- corrupted ciphertext ----------------------------- */

describe("corrupted ciphertext", () => {
  it("fails on a single flipped bit, wherever it is", () => {
    const { aliceState, bobState } = pair();
    const message = ratchetEncrypt(aliceState, utf8("integrity is not optional"));
    for (const field of ["encryptedHeader", "ciphertext"] as const) {
      for (let index = 0; index < message[field].length; index += 7) {
        const damaged = new Uint8Array(message[field]);
        damaged[index] = (damaged[index] ?? 0) ^ 0x01;
        expect(() =>
          ratchetDecrypt(bobState, { ...message, [field]: damaged }),
          `${field}[${index}]`,
        ).toThrow(/failed authentication/);
      }
    }
    // Every one of those attempts left the session untouched.
    expect(new TextDecoder().decode(ratchetDecrypt(bobState, message))).toBe(
      "integrity is not optional",
    );
  });

  it("fails on a truncated or extended ciphertext", () => {
    const { aliceState, bobState } = pair();
    const message = ratchetEncrypt(aliceState, utf8("all of it, or none"));
    for (const ciphertext of [
      message.ciphertext.subarray(0, message.ciphertext.length - 1),
      message.ciphertext.subarray(1),
      new Uint8Array([...message.ciphertext, 0]),
      new Uint8Array(0),
    ]) {
      expect(() => ratchetDecrypt(bobState, { ...message, ciphertext })).toThrow(
        /failed authentication/,
      );
    }
  });

  it("fails on a delivery whose stored bytes were edited", () => {
    const file = encryptFile("order-9", utf8("the artefact"));
    const damaged = new Uint8Array(file.ciphertext);
    damaged[damaged.length - 1] = (damaged.at(-1) ?? 0) ^ 0x80;
    expect(() => decryptFile("order-9", file.key, file.nonce, damaged)).toThrow();
  });
});

/* --------------------------------- wrong key --------------------------------- */

describe("the wrong key", () => {
  it("does not open a vault, a wrapped master key or a file", () => {
    const masterKey = generateMasterKey();
    const sealed = sealVault(masterKey, utf8('{"identity":"secret"}'));
    expect(() => openVault(generateMasterKey(), sealed)).toThrow();

    const password = deriveAccountKeys("alice", "correct horse battery staple", FAST_KDF);
    const wrong = deriveAccountKeys("alice", "correct horse battery stapler", FAST_KDF);
    const envelope = wrapMasterKey(password.wrapKey, masterKey);
    expect(toHex(unwrapMasterKey(password.wrapKey, envelope))).toBe(toHex(masterKey));
    expect(() => unwrapMasterKey(wrong.wrapKey, envelope)).toThrow();

    const file = encryptFile("order-3", utf8("payload"));
    expect(() => decryptFile("order-3", randomBytes(32), file.nonce, file.ciphertext)).toThrow();
  });

  it("derives a different vault key for the same password under a different username", () => {
    const first = deriveAccountKeys("alice", "same password", FAST_KDF);
    const second = deriveAccountKeys("bob", "same password", FAST_KDF);
    expect(toHex(first.wrapKey)).not.toBe(toHex(second.wrapKey));
    expect(toHex(first.authSecret)).not.toBe(toHex(second.authSecret));
    // And the two halves of one password are independent of each other.
    expect(toHex(first.wrapKey)).not.toBe(toHex(first.authSecret));
  });

  it("does not open a message with a neighbouring chain key", () => {
    const { aliceState, bobState } = pair();
    const message = ratchetEncrypt(aliceState, utf8("one"));
    const stranger = pair().bobState;
    stranger.receiveHeaderKey = bobState.receiveHeaderKey;
    // The header key alone is not enough: the message key comes from a chain it lacks.
    expect(() => ratchetDecrypt(stranger, message)).toThrow();
  });
});

/* ------------------------------- wrong identity ------------------------------- */

describe("the wrong identity", () => {
  it("refuses a prekey bundle signed by somebody else's identity", () => {
    const bob = createDeviceIdentity(1);
    const mallory = createDeviceIdentity(1);
    expect(() =>
      openSession(createDeviceIdentity(1).identity, {
        identityKey: bob.identity.publicKey,
        signedPreKeyId: mallory.signedPreKey.keyId,
        signedPreKey: mallory.signedPreKey.keyPair.publicKey,
        signedPreKeySignature: mallory.signedPreKeySignature,
      }),
    ).toThrow(/signature is invalid/);
  });

  it("refuses a low-order public key instead of deriving a predictable secret", () => {
    const identity = createDeviceIdentity(1);
    for (const point of [new Uint8Array(32), Uint8Array.from({ length: 32 }, (_, i) => (i === 0 ? 1 : 0))]) {
      expect(() => dh(identity.signedPreKey.keyPair.privateKey, point)).toThrow(/weak public key/);
    }
  });

  it("does not decrypt when the responder answers with the wrong prekey pair", () => {
    const alice = createDeviceIdentity(1);
    const bob = createDeviceIdentity(1);
    const outgoing = openSession(alice.identity, {
      identityKey: bob.identity.publicKey,
      signedPreKeyId: bob.signedPreKey.keyId,
      signedPreKey: bob.signedPreKey.keyPair.publicKey,
      signedPreKeySignature: bob.signedPreKeySignature,
      oneTimePreKeyId: bob.oneTimePreKeys[0]!.keyId,
      oneTimePreKey: bob.oneTimePreKeys[0]!.keyPair.publicKey,
    });
    const message = encryptText(outgoing.state, "for bob");

    // Same invite, but the responder uses a different one-time prekey than the initiator
    // used: the X3DH secret differs, and nothing about it decrypts.
    const impostor = createDeviceIdentity(2);
    const wrongState = acceptSession(
      bob.identity,
      bob.signedPreKey,
      impostor.oneTimePreKeys[0]!,
      outgoing.invite,
    );
    expect(() => decryptText(wrongState, message)).toThrow();

    // And an entirely different identity answering the same invite gets nothing either.
    const foreign = acceptSession(
      impostor.identity,
      impostor.signedPreKey,
      impostor.oneTimePreKeys[1]!,
      outgoing.invite,
    );
    expect(() => decryptText(foreign, message)).toThrow();
  });

  it("gives two identities a safety number that neither can forge into another's", () => {
    const a = createDeviceIdentity(1).identity.publicKey;
    const b = createDeviceIdentity(1).identity.publicKey;
    const c = createDeviceIdentity(1).identity.publicKey;
    expect(safetyNumber(a, b)).toBe(safetyNumber(b, a));
    expect(safetyNumber(a, b)).not.toBe(safetyNumber(a, c));
  });
});

/* ---------------------------------- nonces ---------------------------------- */

describe("nonces", () => {
  it("shows why they are never reused: the same key and nonce give the same ciphertext", () => {
    const key = randomBytes(32);
    const nonce = randomBytes(NONCE_BYTES);
    const first = aeadEncrypt(key, utf8("aaaaaaaaaaaaaaaa"), new Uint8Array(), nonce);
    const second = aeadEncrypt(key, utf8("aaaaaaaaaaaaaaaa"), new Uint8Array(), nonce);
    expect(toHex(first)).toBe(toHex(second));
  });

  it("never repeats a header nonce or a ciphertext across a long chain", () => {
    const { aliceState } = pair();
    const headerNonces = new Set<string>();
    const ciphertexts = new Set<string>();
    for (let index = 0; index < 300; index += 1) {
      // Identical plaintext every time: any repetition would be the protocol's fault.
      const message = ratchetEncrypt(aliceState, utf8("same message"));
      headerNonces.add(toHex(message.encryptedHeader.subarray(0, NONCE_BYTES)));
      ciphertexts.add(toHex(message.ciphertext));
    }
    expect(headerNonces.size).toBe(300);
    expect(ciphertexts.size).toBe(300);
  });

  it("gives every sealed vault and every wrapped key its own nonce", () => {
    const masterKey = generateMasterKey();
    const nonces = new Set<string>();
    for (let index = 0; index < 50; index += 1) {
      nonces.add(sealVault(masterKey, utf8("{}")).nonce);
      nonces.add(wrapMasterKey(masterKey, generateMasterKey()).nonce);
    }
    expect(nonces.size).toBe(100);
  });
});

/* ------------------------------- session reset ------------------------------- */

describe("session reset", () => {
  it("starts a fresh session that shares nothing with the one it replaces", () => {
    const alice = createDeviceIdentity(2);
    const bob = createDeviceIdentity(2);
    const bundle = (index: number) => ({
      identityKey: bob.identity.publicKey,
      signedPreKeyId: bob.signedPreKey.keyId,
      signedPreKey: bob.signedPreKey.keyPair.publicKey,
      signedPreKeySignature: bob.signedPreKeySignature,
      oneTimePreKeyId: bob.oneTimePreKeys[index]!.keyId,
      oneTimePreKey: bob.oneTimePreKeys[index]!.keyPair.publicKey,
    });

    const first = openSession(alice.identity, bundle(0));
    const firstBob = acceptSession(bob.identity, bob.signedPreKey, bob.oneTimePreKeys[0]!, first.invite);
    const beforeReset = encryptText(first.state, "before the reset");
    expect(decryptText(firstBob, beforeReset)).toBe("before the reset");

    // Alice's device was wiped and set the conversation up again from a new bundle.
    const second = openSession(alice.identity, bundle(1));
    const secondBob = acceptSession(
      bob.identity,
      bob.signedPreKey,
      bob.oneTimePreKeys[1]!,
      second.invite,
    );
    const afterReset = encryptText(second.state, "after the reset");
    expect(decryptText(secondBob, afterReset)).toBe("after the reset");

    // The new session is not the old one: neither state opens the other's traffic, so a
    // message captured before the reset cannot be replayed into the session after it.
    expect(() => decryptText(secondBob, beforeReset)).toThrow();
    expect(() => decryptText(firstBob, afterReset)).toThrow();
    expect(first.invite.ephemeralKey).not.toBe(second.invite.ephemeralKey);
  });

  it("leaves a session untouched when a hostile message fails to open", () => {
    const { aliceState, bobState } = pair();
    const good = ratchetEncrypt(aliceState, utf8("first"));
    const forged = {
      encryptedHeader: randomBytes(NONCE_BYTES + 40 + 16),
      ciphertext: randomBytes(80),
    };
    for (let attempt = 0; attempt < 20; attempt += 1) {
      expect(() => ratchetDecrypt(bobState, forged)).toThrow();
    }
    // Desynchronising a conversation with garbage would be free denial of service.
    expect(new TextDecoder().decode(ratchetDecrypt(bobState, good))).toBe("first");
    const reply = ratchetEncrypt(bobState, utf8("second"));
    expect(new TextDecoder().decode(ratchetDecrypt(aliceState, reply))).toBe("second");
  });

  it("survives a round trip through the wire format", () => {
    const { aliceState, bobState } = pair();
    const message = ratchetEncrypt(aliceState, utf8("through JSON and back"));
    const decoded = decodeMessage(encodeMessage(message));
    expect(new TextDecoder().decode(ratchetDecrypt(bobState, decoded))).toBe("through JSON and back");
  });
});
